  name: spot-mask-env

  channels:
          - https://conda.anaconda.org/menpo
          - conda-forge

  dependencies:
      - tensorflow==2.1
      - tensorboard==2.1
      - pillow==6.1.0
      - python==3.6.8
      - pip==9.0.1

      
      - pip:
        - matplotlib==3.1.1
        - jupyter
        - tqdm==4.45.0
        - opencv-python==4.1.2.30
        - keras==2.3.1
        - numpy==1.18.2
        - pandas==1.0.3
        - scikit-learn==0.22.2.post1
        - torch==1.4.0
        - torchvision==0.5.0